apiVersion : apps/v1
kind: Deployment
metadata:
  name: djangoapp
  labels:
    name: djangoapp
spec:
  selector:
    matchLabels:
      name: djangoapp
  template:
    metadata:
      labels:
        name: djangoapp
    spec:
      containers:
        - name : web
          image: djangoapp
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: djangoapp-secret
          ports:
            - containerPort: 80
              name: djangoapp-web